"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
"""

Term_1 = 1
Term_2 = 2
Term_3 = 0
SumTotal = 0
SumTotal = Term_2

while Term_3 < 4000000:
    Term_3 = Term_2 + Term_1
    Term_1 = Term_2
    Term_2 = Term_3
    if Term_3 % 2 == 0:
        SumTotal = SumTotal + Term_3
        print (SumTotal)
